#!/usr/bin/env python3
"""
pdf_metadata.py — the article's metadata written into its InDesign document, so the exported PDF carries them
(MB, 02.10.2026: title, author, DOI and licence in the PDF itself, for Google Scholar and other readers).

    python3 pdf_metadata.py volumes/<vol>/srom_master_v3.csv <article_id> --out <build dir>
        → <build dir>/<article_id>_metadane.jsx   (run it in InDesign on the article's document, then export the PDF)

One source: the master CSV row (master_schema.md). Written: document title, author(s), subject (the citation line),
keywords, copyright status / notice / licence URL, and the PRISM fields readers look for (doi, url, publicationName,
issn, volume, coverDate, startingPage, endingPage) plus dc:identifier "doi:…". A DOI or URL still holding the
placeholder (XXXXX, todo) is left out and named — never written as if real.
"""
import argparse, csv, json, os, re, sys

PRISM = "http://prismstandard.org/namespaces/basic/2.0/"
DC = "http://purl.org/dc/elements/1.1/"


def placeholder(v):
    return not v or re.search(r"XXXXX|todo|TODO", v) is not None


def licence_name(url, code):
    m = re.search(r"licenses/([a-z-]+)/(\d\.\d)", url or "")
    return f"CC {m.group(1).upper()} {m.group(2)}" if m else (code or "")       # licenses/by-nc-nd/4.0 → CC BY-NC-ND 4.0


def build(row):
    warn = []
    pages = row.get("pages") or "–".join(x for x in (row.get("pages_from"), row.get("pages_to")) if x)
    doi = row.get("doi", "")
    cite = f"{row.get('journal_title', 'Studia Romologica')} {row.get('volume', '')} ({row.get('year', '')})"
    if pages:
        cite += f", s. {pages}"
    if placeholder(doi):
        warn.append(f"DOI not written (placeholder: {doi or 'empty'})")
        doi = ""
    else:
        cite += f". DOI: {doi}"
    kw = [k.strip() for k in re.split(r"[;,]", row.get("keywords_pl", "")) if k.strip()]
    lic = licence_name(row.get("license_url", ""), row.get("license", ""))
    notice = f"© {row.get('year', '')} {row.get('authors_display', '')}" + (f". {lic}" if lic else "")
    if not row.get("license_url"):
        warn.append("licence URL empty")
    props = [("http://ns.adobe.com/pdf/1.3/", "pdf:Keywords", "; ".join(kw)), (PRISM, "prism:publicationName", row.get("journal_title", "")), (PRISM, "prism:issn", row.get("issn", "")),
             (PRISM, "prism:volume", row.get("volume", "")), (PRISM, "prism:coverDate", row.get("year", "")),
             (PRISM, "prism:startingPage", row.get("pages_from", "")), (PRISM, "prism:endingPage", row.get("pages_to", ""))]
    if doi:
        props += [(PRISM, "prism:doi", doi), (DC, "dc:identifier", "doi:" + doi)]
    url = row.get("landing_url", "")
    if placeholder(url):
        if url:
            warn.append(f"landing URL not written (placeholder: {url})")
    else:
        props.append((PRISM, "prism:url", url))
    title = row.get("title_pl", "")
    if not title:
        warn.append("title_pl empty")
    return {"title": title, "author": row.get("authors_display", ""), "subject": cite, "keywords": kw,
            "notice": notice, "licenceUrl": row.get("license_url", ""), "props": [p for p in props if p[2]]}, warn


JSX = r"""// %(id)s_metadane.jsx — generated by srom-quant/scripts/pdf_metadata.py from the master CSV. Writes the article's
// metadata into the document (File > File Info); the PDF export carries them. Run on the article's document, then export.
//@target indesign
var M = %(data)s;
var WARN = %(warn)s;
function main() {
  var doc = (typeof SROM_DOC !== "undefined") ? SROM_DOC : (app.documents.length ? app.activeDocument : null);
  if (!doc) { alert("SROM metadata: no document open."); return "no document"; }
  // PRISM is not a namespace InDesign knows: without registering it, setProperty writes nothing (02.10.2026)
  if (typeof XMPMeta === "undefined") { ExternalObject.AdobeXMPScript = new ExternalObject("lib:AdobeXMPScript"); }
  XMPMeta.registerNamespace("http://prismstandard.org/namespaces/basic/2.0/", "prism");
  var m = doc.metadataPreferences, i, out = [];
  m.documentTitle = M.title; m.author = M.author; m.description = M.subject; m.keywords = M.keywords;
  m.copyrightStatus = CopyrightStatus.YES; m.copyrightNotice = M.notice; m.copyrightInfoURL = M.licenceUrl;
  for (i = 0; i < M.props.length; i++) { m.setProperty(M.props[i][0], M.props[i][1], M.props[i][2]); }
  out.push("SROM metadata — " + doc.name);
  out.push("title: " + m.documentTitle); out.push("author: " + m.author); out.push("subject: " + m.description);
  out.push("licence: " + m.copyrightNotice + " " + m.copyrightInfoURL);
  for (i = 0; i < M.props.length; i++) { out.push(M.props[i][1] + ": " + m.getProperty(M.props[i][0], M.props[i][1])); }
  for (i = 0; i < WARN.length; i++) { out.push("!! " + WARN[i]); }
  out.push(WARN.length ? "RESULT: written, " + WARN.length + " field(s) still missing — fill the master CSV and run again" : "RESULT: OK — export the PDF now");
  var r = out.join("\r");
  if (typeof SROM_DOC === "undefined") { alert(r); }
  return r;
}
main();
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("master"); ap.add_argument("article_id"); ap.add_argument("--out", default=".")
    a = ap.parse_args()
    rows = [{k.lstrip("﻿"): v for k, v in r.items()} for r in csv.DictReader(open(a.master, encoding="utf-8"))]
    row = next((r for r in rows if r["article_id"] == a.article_id), None)
    if row is None:
        sys.exit(f"{a.article_id}: no such row in {a.master}")
    data, warn = build(row)
    os.makedirs(a.out, exist_ok=True)
    path = os.path.join(a.out, a.article_id + "_metadane.jsx")
    open(path, "w", encoding="utf-8").write(JSX % {"id": a.article_id, "data": json.dumps(data, ensure_ascii=True),
                                                   "warn": json.dumps(warn, ensure_ascii=True)})
    print(f"written {path}" + "".join(f"\n!! {w}" for w in warn))


if __name__ == "__main__":
    main()
