// srom_postimport.jsx — generated by build.py. Report-only: changes nothing.
// Run right after placing the DOCX. Confirms the import landed on template styles only,
// with no local overrides, and that no footnote went missing.
//@target indesign

var EXPECTED_TOTAL = /*TOTAL*/;
var PARA_OK = /*PARA*/;
var CHAR_OK = /*CHAR*/;
// kanon § 7.1 asterisk series: markers (character style) in the text, notes (paragraph style) at the end
var AST_CHAR = /*ASTCHAR*/;
var AST_PARA = /*ASTPARA*/;
var AST_MARKS = /*ASTMARKS*/;
var AST_NOTES = /*ASTNOTES*/;
var NA_FORMULA = /[\u2013-]\s*przyp\.\s*(t\u0142um|red)\.\s*$/;

function inList(a, s) { var i; for (i = 0; i < a.length; i++) { if (a[i] === s) { return true; } } return false; }
function inc(o, k) { o[k] = (o[k] || 0) + 1; }
function pageOf(t) {
  try { var f = t.parentTextFrames; return (f && f.length && f[0].parentPage) ? f[0].parentPage.name : "overset"; }
  catch (e) { return "?"; }
}

function grepCount(doc, rx) {
  app.findGrepPreferences = NothingEnum.NOTHING;
  app.findChangeGrepOptions.includeFootnotes = true;
  app.findGrepPreferences.findWhat = rx;
  var n = doc.findGrep().length;
  app.findGrepPreferences = NothingEnum.NOTHING;
  return n;
}

function scanParas(paras, where, st) {
  var i, p, nm, r, j, cs;
  for (i = 0; i < paras.length; i++) {
    p = paras[i];
    nm = p.appliedParagraphStyle.name;
    inc(st.used, nm);
    if (nm === AST_PARA) { st.astParas++; }
    if (!inList(PARA_OK, nm)) { inc(st.foreign, nm); }
    var ov;
    try { ov = p.styleOverridden; } catch (e) { ov = undefined; }
    if (typeof ov === "undefined") { st.noOverrideInfo = true; }
    if (ov === true) {
      st.over++;
      if (st.overList.length < 15) { st.overList.push(where + " p." + pageOf(p) + " [" + nm + "] " + String(p.contents).substr(0, 40)); }
    }
    r = p.textStyleRanges;
    for (j = 0; j < r.length; j++) {
      cs = r[j].appliedCharacterStyle.name;
      if (cs !== "[None]" && cs !== "[Brak]" && !inList(CHAR_OK, cs)) { inc(st.foreignChar, cs); }
      if (cs === AST_CHAR) { st.astMarks += String(r[j].contents).length; }
    }
  }
}

function selectedStory() {
  // text cursor or text frame selected -> that story; nothing usable selected -> null
  try {
    if (app.selection.length) {
      var x = app.selection[0];
      var st = x.parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function main() {
  if (app.documents.length === 0) { alert("SROM post-import: no document open."); return; }
  var doc = app.activeDocument, s, f, i, k, out = [], bad = 0, nFn = 0;
  var st = {used: {}, foreign: {}, foreignChar: {}, over: 0, overList: [], noOverrideInfo: false, astMarks: 0, astParas: 0};
  var naNotes = [];
  // one article in a larger document: put the cursor in its text first; otherwise all stories are checked
  var stories = [];
  var sel = selectedStory();
  if (sel) { stories.push(sel); }
  else { for (s = 0; s < doc.stories.length; s++) { stories.push(doc.stories[s]); } }
  for (s = 0; s < stories.length; s++) {
    scanParas(stories[s].paragraphs, "text", st);
    for (f = 0; f < stories[s].footnotes.length; f++) {
      nFn++;
      scanParas(stories[s].footnotes[f].paragraphs, "note " + (f + 1), st);
      if (NA_FORMULA.test(String(stories[s].footnotes[f].texts[0].contents))) { naNotes.push(nFn); }
    }
  }
  out.push("SROM post-import check — " + doc.name);
  out.push("footnotes: " + nFn + " / expected " + EXPECTED_TOTAL + (nFn === EXPECTED_TOTAL ? "  ok" : "  !! MISMATCH"));
  if (nFn !== EXPECTED_TOTAL) { bad++; }
  out.push("asterisk series: markers " + st.astMarks + " / expected " + AST_MARKS + ", notes " + st.astParas + " / expected " + AST_NOTES +
           ((st.astMarks === AST_MARKS && st.astParas >= AST_NOTES) ? "  ok" : "  !! MISMATCH"));
  if (st.astMarks !== AST_MARKS || st.astParas < AST_NOTES) { bad++; }
  if (naNotes.length) { out.push("!! translator/editorial note(s) among the numbered footnotes: " + naNotes.join(", ")); bad++; }
  out.push("paragraph styles in use:");
  for (k in st.used) { if (st.used.hasOwnProperty(k)) { out.push("   " + k + ": " + st.used[k] + (st.foreign[k] ? "   !! NOT A TEMPLATE STYLE" : "")); if (st.foreign[k]) { bad++; } } }
  for (k in st.foreignChar) { if (st.foreignChar.hasOwnProperty(k)) { out.push("!! foreign character style: " + k + " (" + st.foreignChar[k] + ")"); bad++; } }
  if (st.noOverrideInfo) { out.push("!! this InDesign version does not report overrides — check the Paragraph Styles panel for '+' by hand"); bad++; }
  out.push("paragraphs with local overrides: " + st.over);
  for (i = 0; i < st.overList.length; i++) { out.push("   " + st.overList[i]); }
  if (st.over > 0) { bad++; }
  var checks = [["straight double quote", "\""], ["double space", "  "], ["em dash", "\u2014"], ["three dots", "\\.\\.\\."], ["English opening quote", "\u201C"]];
  for (i = 0; i < checks.length; i++) {
    k = grepCount(doc, checks[i][1]);
    if (k > 0) { out.push("!! " + checks[i][0] + ": " + k); bad++; }
  }
  out.push(bad === 0 ? "RESULT: OK — import is clean" : "RESULT: " + bad + " item(s) need attention");
  alert(out.join("\r"));
}

main();
