// srom_gwiazdki.jsx — generated by build.py for ONE article. Report-only: changes nothing.
// Kanon § 7.1: non-author notes (title note, "– przyp. tłum.", "– przyp. red.") are one series *, **, ***
// restarting on every page, set by hand ABOVE the numbered notes; on the article's first page the title note
// takes the first *. The build typed one "*" per marker; this script says, page by page, how many asterisks each
// marker and its note should get. Run after final layout, with the cursor in the article's text.
//@target indesign

var AST_CHAR = /*ASTCHAR*/;
var AST_MARKS = /*ASTMARKS*/;
var TITLE = /*TITLE*/;
var NOTES = [
/*NOTES*/
];

function stars(n) { var s = "", i; for (i = 0; i < n; i++) { s += "*"; } return s; }

function pageOf(t) {
  try { var f = t.parentTextFrames; return (f && f.length && f[0].parentPage) ? f[0].parentPage.name : "overset"; }
  catch (e) { return "?"; }
}

function mainStory(doc) {
  var best = null, i;
  for (i = 0; i < doc.stories.length; i++) {
    if (best === null || doc.stories[i].footnotes.length > best.footnotes.length) { best = doc.stories[i]; }
  }
  return best;
}

function selectedStory() {
  try {
    if (app.selection.length) {
      var x = app.selection[0];
      var st = x.parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function findChar(doc, name) {
  var a = doc.allCharacterStyles, i;
  for (i = 0; i < a.length; i++) { if (a[i].name === name) { return a[i]; } }
  return null;
}

function main() {
  if (app.documents.length === 0) { alert("SROM asterisk notes: no document open."); return; }
  var doc = app.activeDocument, out = [], bad = 0, i, pg, k, first, n = 0, cs, hits = [];
  var story = selectedStory() || mainStory(doc);
  out.push("SROM asterisk notes (kanon § 7.1) — " + doc.name);
  cs = findChar(doc, AST_CHAR);
  if (!story || !cs) { out.push("!! " + (cs ? "no story" : "character style missing: " + AST_CHAR)); bad++; }
  else {
    app.findTextPreferences = NothingEnum.NOTHING;
    app.findTextPreferences.appliedCharacterStyle = cs;
    hits = story.findText();
    app.findTextPreferences = NothingEnum.NOTHING;
  }
  if (hits.length !== AST_MARKS) { out.push("!! markers found " + hits.length + " / expected " + AST_MARKS); bad++; }
  first = pageOf(story ? story.insertionPoints[0] : null);
  var perPage = {};
  if (TITLE) {
    perPage[first] = 1;
    out.push("p. " + first + "  *   title note: " + NOTES[0]);
  }
  for (i = 0; i < hits.length; i++) {
    pg = pageOf(hits[i]);
    k = (perPage[pg] || 0) + 1;
    perPage[pg] = k;
    n = i + (TITLE ? 1 : 0);
    out.push("p. " + pg + "  " + stars(k) + (k < 3 ? "  " : "") + "  " + (n < NOTES.length ? NOTES[n] : "!! no note text"));
    if (pg === "overset" || pg === "?") { bad++; }
  }
  out.push("Set each marker and the opening of its note to the asterisks shown; notes above the numbered notes, same style.");
  out.push(bad === 0 ? "RESULT: OK" : "RESULT: " + bad + " item(s) need attention");

  var report = out.join("\r"), f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_gwiazdki.txt"); }
  catch (e) { f = new File(Folder.desktop + "/srom_gwiazdki.txt"); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(report); f.close(); }
  alert(report.length > 1500 ? report.substr(0, 1500) + "\r…\rfull report: " + f.fsName : report);
}

main();
