// srom_ibidem_check.jsx — generated by build.py for ONE article. Report-only: changes nothing.
// Kanon §7.3: "Ibidem" only if the preceding note cites the same work AND stands in the same column.
// Run after final layout (File > Scripts panel, double-click). Checks every CSL-generated Ibidem note
// against the note before it: different page / text frame / column => replace by hand with FULL.
// *asterisks* in FULL mark the part to set in the italic character style.
//@target indesign

var EXPECTED_TOTAL = /*TOTAL*/;
var MAP = {
/*MAP*/
};

function pad(n) { return (n < 10 ? "  " : (n < 100 ? " " : "")) + n; }

function mainStory(doc) {
  var best = null, i;
  for (i = 0; i < doc.stories.length; i++) {
    if (best === null || doc.stories[i].footnotes.length > best.footnotes.length) { best = doc.stories[i]; }
  }
  return best;
}

// where does the start of this footnote sit? {ok, page, frame, col}
function locate(fn) {
  var ip, frames, fr, pg, col = 0, b, ins, n, gut, w, x;
  try {
    ip = fn.texts[0].insertionPoints[0];
    frames = ip.parentTextFrames;
    if (!frames || frames.length === 0) { return {ok: false, why: "overset / not laid out"}; }
    fr = frames[0];
    pg = fr.parentPage ? fr.parentPage.name : "?";
    n = fr.textFramePreferences.textColumnCount;
    if (n > 1) {
      b = fr.geometricBounds; // [y1, x1, y2, x2]
      ins = fr.textFramePreferences.insetSpacing;
      gut = fr.textFramePreferences.textColumnGutter;
      x = ip.horizontalOffset - b[1] - (ins instanceof Array ? ins[1] : ins);
      w = (b[3] - b[1] - (ins instanceof Array ? ins[1] + ins[3] : 2 * ins) - (n - 1) * gut) / n;
      col = Math.floor(x / (w + gut));
      if (col < 0) { col = 0; }
      if (col > n - 1) { col = n - 1; }
    }
    return {ok: true, page: pg, frame: fr.id, col: col};
  } catch (e) {
    return {ok: false, why: "error: " + e};
  }
}

function selectedStory() {
  // text cursor or text frame selected -> that story; nothing usable selected -> null
  try {
    if (app.selection.length) {
      var x = app.selection[0];
      var st = x.parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function main() {
  if (app.documents.length === 0) { alert("SROM Ibidem check: no document open."); return; }
  var doc = app.activeDocument;
  // one article in a larger document: put the cursor in its text first
  var story = selectedStory() || mainStory(doc);
  var fns = story ? story.footnotes : [];
  var out = [], bad = 0, checked = 0, k, n, cur, prv, a, b, txt;
  out.push("SROM Ibidem check — " + doc.name);
  out.push("footnotes in main story: " + fns.length + " / expected from build: " + EXPECTED_TOTAL);
  if (fns.length !== EXPECTED_TOTAL) {
    out.push("!! COUNT MISMATCH — numbering below is unreliable; fix the import first.");
    bad++;
  }
  for (k in MAP) {
    if (!MAP.hasOwnProperty(k)) { continue; }
    n = parseInt(k, 10);
    if (n < 2 || n > fns.length) { out.push(pad(n) + "  !! note not found"); bad++; continue; }
    cur = fns[n - 1]; prv = fns[n - 2];
    txt = cur.texts[0].contents;
    if (String(txt).indexOf("Ibidem") < 0) {
      out.push(pad(n) + "  !! expected Ibidem, found: " + String(txt).substr(0, 60)); bad++; continue;
    }
    a = locate(prv); b = locate(cur); checked++;
    if (!a.ok || !b.ok) {
      out.push(pad(n) + "  ?? cannot locate (" + (a.ok ? b.why : a.why) + ") — check by eye"); bad++;
    } else if (a.page !== b.page || a.frame !== b.frame || a.col !== b.col) {
      out.push(pad(n) + "  REPLACE (prev note p." + a.page + " col " + (a.col + 1) + ", this p." + b.page + " col " + (b.col + 1) + ")");
      out.push("       with: " + MAP[k].full); bad++;
    } else {
      out.push(pad(n) + "  ok (p." + b.page + " col " + (b.col + 1) + ")");
    }
  }
  if (checked === 0) { out.push("no CSL Ibidem notes in this article."); }
  out.push(bad === 0 ? "RESULT: OK" : "RESULT: " + bad + " item(s) need attention");

  var report = out.join("\r");
  var f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_ibidem.txt"); }
  catch (e) { f = new File(Folder.desktop + "/srom_ibidem.txt"); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(report); f.close(); }
  alert(report.length > 1500 ? report.substr(0, 1500) + "\r…\rfull report: " + f.fsName : report);
}

main();
