// srom_postimport.jsx — generated by build.py. Report-only: changes nothing.
// Run right after placing the DOCX. Confirms the import landed on template styles only, with no visible
// local formatting, and that no footnote went missing. Every problem is listed again at the end, with what to do.
//@target indesign

var EXPECTED_TOTAL = 7;
var PARA_OK = ["\u015ar\u00f3dtytu\u0142", "\u015ar\u00f3dtytu\u0142 MA\u0141E", "Tekst", "Tekst BEZ WCI\u0118CIA", "Cytat", "Wyliczenie", "Przypis", "\u015ar\u00f3dtytu\u0142", "\u015ar\u00f3dtytu\u0142 MA\u0141E", "Bibliografia", "Podpis", "Tabela TYTU\u0141", "Tekst BEZ WCI\u0118CIA", "Cytat WIERSZ", "Tabela TRE\u015a\u0106", "Przyk\u0142ad FORMA", "Przyk\u0142ad GLOSA", "Przyk\u0142ad PRZEK\u0141AD", "Podpis", "Przypis GWIAZDKOWY", "Wyliczenie", "Motto", "Motto \u0179R\u00d3D\u0141O", "Cytat", "M\u00f3wca", "Afiliacja", "Tytu\u0142", "Autor", "Tekst INICJA\u0141", "Podpis LINIA", "Pagina", "Folio", "Spis tre\u015bci", "Spis AUTOR", "Spis J\u0118ZYKI"];
var CHAR_OK = ["Kursywa", "Kapitaliki", "Pogrubienie", "Proste", "Gwiazdka", "Bez podzia\u0142u", "Kapitaliki GLOSA", "Indeks g\u00f3rny"];
// kanon § 7.1 asterisk series: markers (character style) in the text, notes (paragraph style) at the end
var AST_CHAR = "Gwiazdka";
var AST_PARA = "Przypis GWIAZDKOWY";
var AST_MARKS = 0;
var AST_NOTES = 1;
var NA_FORMULA = /[–-]\s*przyp\.\s*(tłum|red)\.\s*$/;
// what a reader would see: a paragraph attribute that differs from its style. InDesign's own "override" flag
// (styleOverridden) is not used: after a Word import it is set on paragraphs whose stored text carries no
// difference at all (Ostendorf test, 02.10.2026: 54 flags, none of them in the saved IDML).
var PARA_ATTR = ["justification", "leftIndent", "rightIndent", "firstLineIndent", "spaceBefore", "spaceAfter", "alignToBaseline"];
var RUN_ATTR = ["pointSize"];   // with the font below: what a Word import carries (each property read costs time)

function inList(a, s) { var i; for (i = 0; i < a.length; i++) { if (a[i] === s) { return true; } } return false; }
function inc(o, k) { o[k] = (o[k] || 0) + 1; }
function pageOf(t) {
  try { var f = t.parentTextFrames; return (f && f.length && f[0].parentPage) ? f[0].parentPage.name : "overset"; }
  catch (e) { return "?"; }
}
// a Font or a style answers .name; an enumeration value throws on it and is compared as its number
function val(x) { try { return (x && typeof x === "object" && x.name !== undefined) ? String(x.name) : String(x); } catch (e) { return String(x); } }

// the story's footnotes in text order: story.footnotes is not always in that order (after placing into a
// threaded template it may start mid-text and wrap round; 02.10.2026)
function notesInOrder(story) {
  var a = [], i, f = story.footnotes;
  for (i = 0; i < f.length; i++) { a.push(f[i]); }
  a.sort(function (x, y) { return x.storyOffset.index - y.storyOffset.index; });
  return a;
}

function grepCount(doc, rx) {
  app.findGrepPreferences = NothingEnum.NOTHING;
  app.findChangeGrepOptions.includeFootnotes = true;
  app.findGrepPreferences.findWhat = rx;
  var n = doc.findGrep().length;
  app.findGrepPreferences = NothingEnum.NOTHING;
  return n;
}

function noteLocal(st, what, where) {
  inc(st.local, what);
  if (!st.localWhere[what]) { st.localWhere[what] = []; }
  if (st.localWhere[what].length < 3) { st.localWhere[what].push(where); }
}

function scanParas(paras, where, st) {
  var i, p, ps, nm, r, j, cs, a, k, w;
  for (i = 0; i < paras.length; i++) {
    p = paras[i];
    ps = p.appliedParagraphStyle;
    nm = ps.name;
    inc(st.used, nm);
    if (nm === AST_PARA) { st.astParas++; }
    if (!inList(PARA_OK, nm)) { inc(st.foreign, nm); }
    w = where + " [" + nm + "] " + String(p.contents).substr(0, 30);
    for (a = 0; a < PARA_ATTR.length; a++) {
      k = PARA_ATTR[a];
      try { if (val(p[k]) !== val(ps[k])) { noteLocal(st, nm + ": " + k + " " + val(p[k]) + " (style: " + val(ps[k]) + ")", w); } } catch (e) {}
    }
    r = p.textStyleRanges;
    for (j = 0; j < r.length; j++) {
      cs = r[j].appliedCharacterStyle.name;
      if (cs !== "[None]" && cs !== "[Brak]" && !inList(CHAR_OK, cs)) { inc(st.foreignChar, cs); }
      if (cs === AST_CHAR) { st.astMarks += String(r[j].contents).length; }
      if (cs === "[None]" || cs === "[Brak]") {
        for (a = 0; a < RUN_ATTR.length; a++) {
          k = RUN_ATTR[a];
          try { if (val(r[j][k]) !== val(ps[k])) { noteLocal(st, nm + ": text " + k + " " + val(r[j][k]) + " (style: " + val(ps[k]) + ")", w); } } catch (e2) {}
        }
        try { if (r[j].appliedFont.name !== ps.appliedFont.name || r[j].fontStyle !== ps.fontStyle) { noteLocal(st, nm + ": text font " + r[j].appliedFont.name + " (style: " + ps.appliedFont.name + ")", w); } } catch (e3) {}
      }
    }
  }
}

function selectedStory() {
  // text cursor or text frame selected -> that story; nothing usable selected -> null
  try {
    if (app.selection.length) {
      var x = app.selection[0];
      var st = x.parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function main() {
  if (app.documents.length === 0) { alert("SROM post-import: no document open."); return; }
  var doc = app.activeDocument, s, f, i, k, out = [], todo = [], nFn = 0;
  var st = {used: {}, foreign: {}, foreignChar: {}, local: {}, localWhere: {}, astMarks: 0, astParas: 0};
  var naNotes = [];
  // one article in a larger document: put the cursor in its text first; otherwise all stories are checked
  var stories = [];
  var sel = selectedStory();
  if (sel) { stories.push(sel); }
  else { for (s = 0; s < doc.stories.length; s++) { stories.push(doc.stories[s]); } }
  for (s = 0; s < stories.length; s++) {
    scanParas(stories[s].paragraphs, "text", st);
    var fns = notesInOrder(stories[s]);
    for (f = 0; f < fns.length; f++) {
      nFn++;
      scanParas(fns[f].paragraphs, "note " + (f + 1), st);
      if (NA_FORMULA.test(String(fns[f].texts[0].contents))) { naNotes.push(nFn); }
    }
  }
  out.push("SROM post-import check — " + doc.name);
  out.push("footnotes: " + nFn + " / expected " + EXPECTED_TOTAL + (nFn === EXPECTED_TOTAL ? "  ok" : "  !! MISMATCH"));
  if (nFn !== EXPECTED_TOTAL) { todo.push("footnotes: " + nFn + " placed, " + EXPECTED_TOTAL + " expected — re-place the DOCX with Footnotes ticked in the import options"); }
  out.push("asterisk series: markers " + st.astMarks + " / expected " + AST_MARKS + ", notes " + st.astParas + " / expected " + AST_NOTES +
           ((st.astMarks === AST_MARKS && st.astParas >= AST_NOTES) ? "  ok" : "  !! MISMATCH"));
  if (st.astMarks !== AST_MARKS || st.astParas < AST_NOTES) { todo.push("asterisk series: markers or notes missing — compare with the build report"); }
  if (naNotes.length) { out.push("!! translator/editorial note(s) among the numbered footnotes: " + naNotes.join(", ")); todo.push("notes " + naNotes.join(", ") + " end in 'przyp. tłum./red.': they belong to the asterisk series, not the numbered notes — tell srom-produkcja"); }
  out.push("paragraph styles in use:");
  for (k in st.used) { if (st.used.hasOwnProperty(k)) { out.push("   " + k + ": " + st.used[k] + (st.foreign[k] ? "   !! NOT A TEMPLATE STYLE" : "")); if (st.foreign[k]) { todo.push("style '" + k + "' is not a template style — the DOCX and the template disagree on names; tell srom-produkcja"); } } }
  for (k in st.foreignChar) { if (st.foreignChar.hasOwnProperty(k)) { out.push("!! foreign character style: " + k + " (" + st.foreignChar[k] + ")"); todo.push("character style '" + k + "' is not a template style — tell srom-produkcja"); } }
  // a style name twice (one at the root, one in a folder) = the import made its own copy instead of using the template's
  var seen = {}, all = doc.allParagraphStyles, dup = [], extra = [];
  for (i = 0; i < all.length; i++) {
    k = all[i].name;
    if (seen[k]) { dup.push(k); } else { seen[k] = true; }
    if (k.charAt(0) !== "[" && !inList(PARA_OK, k)) { extra.push(k); }
  }
  for (i = 0; i < dup.length; i++) { out.push("!! style '" + dup[i] + "' exists twice"); todo.push("style '" + dup[i] + "' exists twice: the import made its own copy. Paragraph Styles panel: delete the copy at the top level and replace it with the template's"); }
  if (extra.length) { out.push("info: styles brought by the import, not in use: " + extra.join(", ") + " (may be deleted)"); }
  var nLocal = 0;
  for (k in st.local) { if (st.local.hasOwnProperty(k)) { nLocal += st.local[k]; } }
  out.push("local formatting (differs from the style): " + nLocal);
  for (k in st.local) {
    if (st.local.hasOwnProperty(k)) {
      out.push("   !! " + k + " × " + st.local[k] + "   e.g. " + st.localWhere[k].join(" | "));
      todo.push(k + " × " + st.local[k] + " — select the text, Paragraph Styles panel: Clear Overrides; then tell srom-produkcja");
    }
  }
  // GREP: ~" is the straight double quote (a bare " matches every double quote, curly ones included)
  var checks = [["straight double quote", "~\""], ["double space", "  "], ["em dash", "—"], ["three dots", "\\.\\.\\."], ["English opening quote", "“"]];
  for (i = 0; i < checks.length; i++) {
    k = grepCount(doc, checks[i][1]);
    if (k > 0) { out.push("!! " + checks[i][0] + ": " + k); todo.push(checks[i][0] + " × " + k + " — Find/Change (GREP) " + checks[i][1] + " to see them; the DOCX should have none: tell srom-produkcja"); }
  }
  if (todo.length === 0) { out.push("RESULT: OK — import is clean"); }
  else {
    out.push("");
    out.push("RESULT: " + todo.length + " item(s) need attention:");
    for (i = 0; i < todo.length; i++) { out.push("  " + (i + 1) + ". " + todo[i]); }
  }

  var report = out.join("\r"), file;
  try { file = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_postimport.txt"); }
  catch (e) { file = new File(Folder.desktop + "/srom_postimport.txt"); }
  file.encoding = "UTF-8";
  if (file.open("w")) { file.write(report); file.close(); }
  if (report.length > 1800) {
    // a long report: the attention list must stay visible, so the middle is cut, not the end
    var head = out.slice(0, 3).join("\r"), tail = out.slice(out.length - todo.length - 2).join("\r");
    report = head + "\r…\r" + tail + "\r\rfull report: " + file.fsName;
  }
  alert(report);
}

main();
