// srom_gwiazdki.jsx — generated by build.py for ONE article. Reports, then offers to apply (asks first).
// Kanon § 7.1: non-author notes (title note, "– przyp. tłum.", "– przyp. red.") are one series *, **, ***
// restarting on every page, set by hand ABOVE the numbered notes; on the article's first page the title note
// takes the first *. The build typed one "*" per marker; this script says, page by page, how many asterisks each
// marker and its note should get. Run after final layout, with the cursor in the article's text.
//@target indesign

var AST_CHAR = "Gwiazdka";
var AST_PARA = "Przypis GWIAZDKOWY";
var AST_MARKS = 0;
var TITLE = true;
var NOTES = [
  "* Pierwodruk: A. Ostendorf, *Familiar Outsiders Abroad: Relational Rac"
];


// After the report the script offers to make the changes itself (MB, 02.10.2026): one undo step (Edit > Undo).
// SROM_APPLY = true / false set before running skips the question (tests).
function wantApply(n, what) {
  if (n === 0) { return false; }
  if (typeof SROM_APPLY !== "undefined") { return SROM_APPLY === true; }
  return confirm("SROM: " + what + " (" + n + ")?\rOne undo step: Edit > Undo reverses all of it.");
}
function stars(n) { var s = "", i; for (i = 0; i < n; i++) { s += "*"; } return s; }

function pageOf(t) {
  try { var f = t.parentTextFrames; return (f && f.length && f[0].parentPage) ? f[0].parentPage.name : "overset"; }
  catch (e) { return "?"; }
}

function mainStory(doc) {
  var best = null, i;
  for (i = 0; i < doc.stories.length; i++) {
    if (best === null || doc.stories[i].footnotes.length > best.footnotes.length) { best = doc.stories[i]; }
  }
  return best;
}

function selectedStory() {
  try {
    if (app.selection.length) {
      var x = app.selection[0];
      var st = x.parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function findChar(doc, name) {
  var a = doc.allCharacterStyles, i;
  for (i = 0; i < a.length; i++) { if (a[i].name === name) { return a[i]; } }
  return null;
}

function main() {
  if (app.documents.length === 0) { alert("SROM asterisk notes: no document open."); return; }
  var doc = app.activeDocument, out = [], todo = [], bad = 0, i, pg, k, first, n = 0, cs, hits = [];
  var story = selectedStory() || mainStory(doc);
  out.push("SROM asterisk notes (kanon § 7.1) — " + doc.name);
  out.push("Each line = one marker and its note, with the asterisks they must get.");
  cs = findChar(doc, AST_CHAR);
  if (!story || !cs) { out.push("!! " + (cs ? "no story" : "character style missing: " + AST_CHAR)); bad++; }
  else {
    app.findTextPreferences = NothingEnum.NOTHING;
    app.findTextPreferences.appliedCharacterStyle = cs;
    hits = story.findText();
    app.findTextPreferences = NothingEnum.NOTHING;
  }
  if (hits.length !== AST_MARKS) { out.push("!! markers found " + hits.length + " / expected " + AST_MARKS); bad++; }
  // the asterisk notes, in text order: note 0 = title note (if any), then one per marker
  var astNotes = [], ps = story ? story.paragraphs : [], fix = [];
  for (i = 0; i < ps.length; i++) { if (ps[i].appliedParagraphStyle.name === AST_PARA) { astNotes.push(ps[i]); } }
  first = pageOf(story ? story.insertionPoints[0] : null);
  var perPage = {};
  if (TITLE) {
    perPage[first] = 1;
    out.push("p. " + first + "  *   title note: " + NOTES[0]);
  }
  for (i = 0; i < hits.length; i++) {
    pg = pageOf(hits[i]);
    k = (perPage[pg] || 0) + 1;
    perPage[pg] = k;
    n = i + (TITLE ? 1 : 0);
    out.push("p. " + pg + "  " + stars(k) + (k < 3 ? "  " : "") + "  " + (n < NOTES.length ? NOTES[n] : "!! no note text"));
    var lead = n < astNotes.length ? (String(astNotes[n].contents).match(/^\*+/) || [""])[0] : stars(k);
    if (String(hits[i].contents) !== stars(k) || lead !== stars(k)) { fix.push([hits[i], n < astNotes.length ? astNotes[n] : null, lead.length, k]); }
    if (k > 1 && (String(hits[i].contents) !== stars(k) || lead !== stars(k))) { todo.push("p. " + pg + ": the marker in the text and the opening of its note → " + stars(k) + " (now *)  " + (n < NOTES.length ? NOTES[n].substr(0, 40) : "")); }
    if (pg === "overset" || pg === "?") { bad++; }
  }
  out.push("");
  if (bad) { out.push("RESULT: " + bad + " item(s) need attention (lines marked !! or on an overset page above)"); }
  if (todo.length) {
    out.push("TO DO (" + todo.length + "):");
    for (i = 0; i < todo.length; i++) { out.push("  " + (i + 1) + ". " + todo[i]); }
  } else if (!bad) {
    out.push("RESULT: OK — every marker and note has its asterisks");
  }
  out.push("Asterisk notes stand above the numbered notes of their page, in Przypis GWIAZDKOWY.");

  if (wantApply(fix.length, "set the asterisks of the markers and notes listed")) {
    app.doScript(function () {
      var j, x;
      for (j = 0; j < fix.length; j++) {
        x = fix[j];
        x[0].contents = stars(x[3]);
        if (x[1] && x[2] > 0) { x[1].characters.itemByRange(0, x[2] - 1).contents = stars(x[3]); }
        else if (x[1]) { x[1].insertionPoints[0].contents = stars(x[3]) + " "; }
      }
    }, ScriptLanguage.JAVASCRIPT, undefined, UndoModes.ENTIRE_SCRIPT, "SROM asterisks");
    out.push("APPLIED: " + fix.length + " marker(s) and note(s) set (Edit > Undo reverses it). Moving the notes above the numbered notes of their page stays by hand.");
  }
  var report = out.join("\r"), f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_gwiazdki.txt"); }
  catch (e) { f = new File(Folder.desktop + "/srom_gwiazdki.txt"); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(report); f.close(); }
  if (report.length > 1800) {
    report = out.slice(0, 2).join("\r") + "\r…\r" + out.slice(out.length - todo.length - 3).join("\r") + "\r\rfull report: " + f.fsName;
  }
  alert(report);
}

main();
