// srom_doi.jsx — generated by build.py for ONE article (SYS-5, MB 02.10.2026). Reports, then offers to apply (asks first).
// Every citation in the notes and every bibliography entry whose work has a DOI gets an invisible hyperlink to
// https://doi.org/… (encoded by the build); nothing is printed (GEN-10: no DOIs in print).
// Run LAST, after the Ibidem, asterisk and final-pass scripts, right before the PDF export: the links sit on the
// text, so they follow reflow, but text retyped afterwards loses its link. Running it again replaces the links it
// made before (and only those). One undo step.
// PDF export: tick "Hyperlinks" (General > Include), as for "Bookmarks", or the links are not written.
//@target indesign

var EXPECTED_TOTAL = 7;
var BIB_STYLE = "Bibliografia";
var AST_STYLE = "Przypis GWIAZDKOWY";
// footnote number -> [[citation text as printed, URL, key], …]
var NOTES = {
  "1": [["P. Galletti, Los Gitanos como Otro y como Horizonte de Otredad en la Hispanoam\u00e9ria Colonial (S. XV a XIX), \u201eInternational Journal of Roma Studies\u201d, 2021, t. 3, nr 2, s. 119.", "https://doi.org/10.17583/ijrs.8527", "galletti2021"]],
  "2": [["T. Herzog, Indigenous Reducciones and Spanish Resettlement: Placing Colonial and European History in Dialogue, \u201eLer Hist\u00f3ria\u201d, 2018, t. 72", "https://doi.org/10.4000/lerhistoria.3146", "herzog2018"]],
  "3": [["D. Wakeley-Smith, \u201eThe One Primitive People Who Contact with Civilization has Failed to Exterminate\u201d: New York and \u201eGypsy\u201d Madness in the 1920s, \u201eJournal of American Ethnic History\u201d, 2023, t. 43, nr 1", "https://doi.org/10.5406/19364695.43.1.03", "wakeleysmith2023"]],
  "7": [["K. Trumpener, The Time of the Gypsies: A \u201ePeople without History\u201d in the Narratives of the West, \u201eCritical Inquiry\u201d, 1992, t. 18, nr 4.", "https://doi.org/10.1086/448659", "trumpener1992"]]
};
// citations in the asterisk notes (title note, translator's notes)
var AST = [

];
// bibliography entries: [[entry text as printed, URL, key], …]
var BIB = [
  ["Galletti Patricia, Los Gitanos como Otro y como Horizonte de Otredad en la Hispanoam\u00e9ria Colonial (S. XV a XIX), \u201eInternational Journal of Roma Studies\u201d, 2021, t. 3, nr 2.", "https://doi.org/10.17583/ijrs.8527", "galletti2021"],
  ["Herzog Tamar, Indigenous Reducciones and Spanish Resettlement: Placing Colonial and European History in Dialogue, \u201eLer Hist\u00f3ria\u201d, 2018, t. 72, s. 9\u201330.", "https://doi.org/10.4000/lerhistoria.3146", "herzog2018"],
  ["Trumpener Katie, The Time of the Gypsies: A \u201ePeople without History\u201d in the Narratives of the West, \u201eCritical Inquiry\u201d, 1992, t. 18, nr 4, s. 843\u2013884.", "https://doi.org/10.1086/448659", "trumpener1992"],
  ["Wakeley-Smith Dalen, \u201eThe One Primitive People Who Contact with Civilization has Failed to Exterminate\u201d: New York and \u201eGypsy\u201d Madness in the 1920s, \u201eJournal of American Ethnic History\u201d, 2023, t. 43, nr 1, s. 67\u201387.", "https://doi.org/10.5406/19364695.43.1.03", "wakeleysmith2023"]
];
var PREFIX = "srom-doi ";            // names of the hyperlinks, sources and destinations this script creates

// text as compared: no soft hyphens or zero-width characters, every kind of space one plain space; map[i] = the
// index of normalised character i in the original (InDesign's character index)
function norm(s) {
  var t = [], map = [], i, c, prevSpace = false;
  s = String(s);
  for (i = 0; i < s.length; i++) {
    c = s.charAt(i);
    if (/[­​‌‍⁠﻿]/.test(c)) { continue; }
    if (/[\s  -   　]/.test(c)) {
      if (prevSpace) { continue; }
      c = " "; prevSpace = true;
    } else { prevSpace = false; }
    t.push(c); map.push(i);
  }
  return {t: t.join(""), map: map};
}

function trim(s) { return String(s).replace(/^\s+|\s+$/g, ""); }

// [first, last] character index of needle in raw at or after raw index `from`, or null
function find(raw, needle, from) {
  var N = norm(raw), m = trim(norm(needle).t), k, start = 0;
  if (!m) { return null; }
  for (k = 0; k < N.map.length; k++) { if (N.map[k] >= from) { start = k; break; } start = N.map.length; }
  k = N.t.indexOf(m, start);
  if (k < 0) { return null; }
  return [N.map[k], N.map[k + m.length - 1]];
}

// the story's footnotes in text order (story.footnotes is not always in that order; 02.10.2026)
function notesInOrder(story) {
  var a = [], i, f = story.footnotes;
  for (i = 0; i < f.length; i++) { a.push(f[i]); }
  a.sort(function (x, y) { return x.storyOffset.index - y.storyOffset.index; });
  return a;
}

function mainStory(doc) {
  var best = null, i;
  for (i = 0; i < doc.stories.length; i++) {
    if (best === null || doc.stories[i].footnotes.length > best.footnotes.length) { best = doc.stories[i]; }
  }
  return best;
}

function selectedStory() {
  try {
    if (app.selection.length) {
      var st = app.selection[0].parentStory;
      if (st && st.isValid) { return st; }
    }
  } catch (e) {}
  return null;
}

function wantApply(n, what) {
  if (n === 0) { return false; }
  if (typeof SROM_APPLY !== "undefined") { return SROM_APPLY === true; }
  return confirm("SROM: " + what + " (" + n + ")?\rOne undo step: Edit > Undo reverses all of it.");
}

function cut(s, n) { s = trim(s); return s.length > n ? s.substr(0, n - 1) + "…" : s; }

function removeOld(doc) {
  var i, n = 0, h, src, l;
  l = doc.hyperlinks;
  for (i = l.length - 1; i >= 0; i--) {
    h = l[i];
    if (h.name.indexOf(PREFIX) !== 0) { continue; }
    src = null;
    try { src = h.source; } catch (e) {}
    h.remove(); n++;
    try { if (src && src.isValid) { src.remove(); } } catch (e2) {}
  }
  l = doc.hyperlinkTextSources;
  for (i = l.length - 1; i >= 0; i--) { if (l[i].name.indexOf(PREFIX) === 0) { l[i].remove(); } }
  l = doc.hyperlinkURLDestinations;
  for (i = l.length - 1; i >= 0; i--) { if (l[i].name.indexOf(PREFIX) === 0) { l[i].remove(); } }
  return n;
}

// plan: [{owner (footnote or paragraph), a, b, url, label}]. One hidden destination per link: InDesign does not let
// two hyperlinks share a hidden one (02.10.2026), and a shared visible one would fill the Hyperlinks panel.
function make(doc, plan) {
  var i, p, d, src, h, made = 0, fail = [];
  for (i = 0; i < plan.length; i++) {
    p = plan[i]; d = null; src = null;
    try {
      d = doc.hyperlinkURLDestinations.add(p.url, {name: PREFIX + "url " + (i + 1), hidden: true});
      src = doc.hyperlinkTextSources.add(p.owner.characters.itemByRange(p.a, p.b), {name: PREFIX + (i + 1)});
      h = doc.hyperlinks.add(src, d, {name: PREFIX + (i + 1)});
      h.visible = false;
      try { h.highlight = HyperlinkAppearanceHighlight.NONE; } catch (e1) {}
      made++;
    } catch (e) {
      fail.push(p.label + ": " + e);
      try { if (src && src.isValid) { src.remove(); } } catch (e2) {}
      try { if (d && d.isValid) { d.remove(); } } catch (e3) {}
    }
  }
  return {made: made, fail: fail};
}

function main() {
  var doc = (typeof SROM_DOC !== "undefined") ? SROM_DOC : (app.documents.length ? app.activeDocument : null);
  if (!doc) { alert("SROM DOI links: no document open."); return "no document"; }
  var story = (typeof SROM_DOC === "undefined" && selectedStory()) || mainStory(doc);
  var fns = story ? notesInOrder(story) : [];
  var out = [], todo = [], plan = [], k, i, j, n, raw, r, from, items, whole, ps, nn = 0, na = 0, nb = 0, want = 0;
  out.push("SROM DOI links — " + doc.name);
  out.push("footnotes in main story: " + fns.length + " / expected from build: " + EXPECTED_TOTAL);

  // 1. footnotes: each citation's text inside its own note
  if (fns.length !== EXPECTED_TOTAL) {
    out.push("!! COUNT MISMATCH — no links in the notes (the numbering is unreliable); fix the import first.");
    for (k in NOTES) { if (NOTES.hasOwnProperty(k)) { want += NOTES[k].length; todo.push("note " + k + ": not linked (footnote count differs from the build)"); } }
  } else {
    for (k in NOTES) {
      if (!NOTES.hasOwnProperty(k)) { continue; }
      n = parseInt(k, 10); items = NOTES[k]; want += items.length;
      raw = String(fns[n - 1].texts[0].contents); from = 0;
      for (i = 0; i < items.length; i++) {
        r = find(raw, items[i][0], from);
        whole = false;
        if (!r && items.length === 1) {
          // the note was changed in InDesign (an Ibidem retyped in full): one work cited, so the note is the link
          r = [0, raw.length - 1];
          while (r[0] < raw.length && /[\s\u0000-\u001F - ]/.test(raw.charAt(r[0]))) { r[0]++; }
          whole = r[0] < raw.length;
        }
        if (!r || r[0] > r[1]) { todo.push("note " + n + ": text not found, not linked — " + cut(items[i][0], 70) + " (" + items[i][2] + ")"); continue; }
        plan.push({owner: fns[n - 1], a: r[0], b: r[1], url: items[i][1], label: "note " + n + " " + items[i][2]});
        nn++; from = r[1] + 1;
        if (whole) { out.push("   note " + n + ": text changed since the build — the whole note links to " + items[i][1]); }
      }
    }
  }

  // 2. asterisk notes: paragraphs in their style anywhere in the story
  ps = [];
  if (story) { for (i = 0; i < story.paragraphs.length; i++) { if (story.paragraphs[i].appliedParagraphStyle.name === AST_STYLE) { ps.push(story.paragraphs[i]); } } }
  for (i = 0; i < AST.length; i++) {
    want++; r = null;
    for (j = 0; j < ps.length && !r; j++) {
      r = find(String(ps[j].contents), AST[i][0], 0);
      if (r) { plan.push({owner: ps[j], a: r[0], b: r[1], url: AST[i][1], label: "asterisk note " + AST[i][2]}); na++; }
    }
    if (!r) { todo.push("asterisk note: text not found, not linked — " + cut(AST[i][0], 70) + " (" + AST[i][2] + ")"); }
  }

  // 3. bibliography: the whole entry, matched on its text (else on its first 40 characters, if only one entry has them)
  ps = [];
  for (j = 0; j < doc.stories.length; j++) {
    var sp = doc.stories[j].paragraphs;
    for (i = 0; i < sp.length; i++) { if (sp[i].appliedParagraphStyle.name === BIB_STYLE) { ps.push(sp[i]); } }
  }
  var used = {}, texts = [];
  for (j = 0; j < ps.length; j++) { texts.push(trim(norm(ps[j].contents).t)); }
  for (i = 0; i < BIB.length; i++) {
    want++;
    var e = trim(norm(BIB[i][0]).t), hit = -1, cand = [];
    for (j = 0; j < texts.length; j++) { if (!used[j] && texts[j] === e) { hit = j; break; } }
    if (hit < 0) {
      for (j = 0; j < texts.length; j++) { if (!used[j] && texts[j].substr(0, 40) === e.substr(0, 40)) { cand.push(j); } }
      if (cand.length === 1) { hit = cand[0]; out.push("   bibliography: entry changed since the build, matched on its start — " + cut(BIB[i][0], 60)); }
    }
    if (hit < 0) { todo.push("bibliography: entry not found, not linked — " + cut(BIB[i][0], 70) + " (" + BIB[i][2] + ")"); continue; }
    used[hit] = true;
    raw = String(ps[hit].contents);
    r = [0, raw.length - 1];
    while (r[1] > 0 && /[\r\n\s]/.test(raw.charAt(r[1]))) { r[1]--; }
    plan.push({owner: ps[hit], a: r[0], b: r[1], url: BIB[i][1], label: "bibliography " + BIB[i][2]});
    nb++;
  }

  out.push("to link: " + nn + " citation(s) in footnotes, " + na + " in asterisk notes, " + nb + " bibliography entr" + (nb === 1 ? "y" : "ies") + " — " + plan.length + " of " + want);
  if (wantApply(plan.length, "add " + plan.length + " invisible DOI link(s)")) {
    var old = 0, res = {made: 0, fail: []};
    app.doScript(function () { old = removeOld(doc); res = make(doc, plan); },
                 ScriptLanguage.JAVASCRIPT, undefined, UndoModes.ENTIRE_SCRIPT, "SROM DOI links");
    out.push("APPLIED: " + res.made + " link(s) made" + (old ? " (" + old + " old ones replaced)" : "") + ". Export the PDF with General > Include > Hyperlinks ticked.");
    for (i = 0; i < res.fail.length; i++) { todo.push("not made: " + res.fail[i]); }
  }
  if (todo.length === 0) { out.push("RESULT: OK"); }
  else {
    out.push("");
    out.push("RESULT: " + todo.length + " item(s) need attention:");
    for (i = 0; i < todo.length; i++) { out.push("  " + (i + 1) + ". " + todo[i]); }
  }
  var report = out.join("\r"), f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_doi.txt"); }
  catch (e2) { f = new File(Folder.desktop + "/srom_doi.txt"); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(report); f.close(); }
  if (typeof SROM_DOC === "undefined") {
    alert(report.length > 1800 ? out.slice(0, 3).join("\r") + "\r…\r" + out.slice(out.length - Math.min(todo.length, 12) - 2).join("\r") + "\r\rfull report: " + f.fsName : report);
  }
  return report;
}

main();
