// srom_style_setup.jsx — SROM house style v3 in the ACTIVE document.
// Generated by scripts/make_style_setup.py from indesign/style_spec.json — do not edit by hand.
// Meant for a blank document or a copy of an old one (margins, masters). What it does:
//   1. document settings: baseline grid 13.2945 pt from 62.362 pt, Footnote Options, superscript/small-cap sizes;
//   2. PURGE: every existing paragraph/character style is replaced by the house set — text in an old style
//      takes its new style (Tekst → Tekst, Podrozdzial → Śródtytuł, Bez wciecia → Tekst BEZ WCIĘCIA …),
//      anything unknown becomes Tekst / no character style;
//   3. creates the house styles in panel order (working set at the top, folders "Rzadkie" and "Numer"),
//      with their values, GREP styles (non-breaking spaces, kanon § 3.3) and nested styles;
//   4. reads every value back and reports what did not take.
// A report is shown and saved next to the document (<name>_style_setup.txt; unsaved document: on the Desktop).
// Previous version (v2, renaming script): indesign/legacy/v2/.
//@target indesign

var SPEC = /*SPEC*/;
var LOG = [];
var PREFIX = "~stary~ ";
var DOC = null;               // the document being set up
function log(s) { LOG.push(s); }

var ENUMS = {
  justification: "Justification", singleWordJustification: "SingleWordJustification", capitalization: "Capitalization",
  position: "Position", gridAlignment: "GridAlignment", bulletsAndNumberingListType: "ListType",
  diacriticPosition: "DiacriticPositionOptions", leading: "Leading", markerPositioning: "FootnoteMarkerPositioning",
  footnoteNumberingStyle: "FootnoteNumberingStyle", restartNumbering: "FootnoteRestarting",
  showPrefixSuffix: "FootnotePrefixSuffix", footnoteFirstBaselineOffset: "FootnoteFirstBaseline",
  baselineGridRelativeOption: "BaselineGridRelativeOption", alignment: "TabStopAlignment", delimiter: "NestedStyleDelimiters"
};

function val(k, v) {
  if (typeof v === "string" && ENUMS[k] && /^[A-Z_]+$/.test(v)) {
    var cls = $.global[ENUMS[k]];
    if (cls && cls[v] !== undefined) { return cls[v]; }
    throw new Error("unknown constant " + ENUMS[k] + "." + v);
  }
  return v;
}
function same(a, b) {
  if (typeof a === "number" && typeof b === "number") { return Math.abs(a - b) < 0.001; }
  return String(a) === String(b);
}
// values are set in spec order; one that InDesign refuses because of another (minimum letter spacing above the
// desired one, say) is tried again once all the others are in
function setAll(obj, props, what) {
  var k, later = [], i;
  for (k in props) {
    if (!props.hasOwnProperty(k)) { continue; }
    try { obj[k] = val(k, props[k]); } catch (e) { later.push(k); }
  }
  for (i = 0; i < later.length; i++) {
    k = later[i];
    try { obj[k] = val(k, props[k]); } catch (e2) { log("   ! " + what + ": " + k + " = " + props[k] + " (" + e2 + ")"); }
  }
}
// read back: every value in the spec must hold in the style (fonts by family name)
function check(obj, props, what) {
  var k, want, got, bad = 0;
  for (k in props) {
    if (!props.hasOwnProperty(k)) { continue; }
    try {
      want = val(k, props[k]); got = obj[k];
      if (k === "appliedFont") { got = typeof obj.appliedFont === "string" ? obj.appliedFont.split("\t")[0] : obj.appliedFont.fontFamily; }
      else if (k === "appliedLanguage") { got = obj.appliedLanguage.name; }
      else if (k === "footnoteTextStyle" || k === "footnoteMarkerStyle") { got = obj[k].name; want = props[k] === null ? DOC.characterStyles[0].name : props[k]; }
      else if (/(Color|Type)$/.test(k)) { got = got.name; }   // swatch, stroke style: compared by name
      if (!same(got, want)) { bad++; log("   ! " + what + ": " + k + " is " + got + ", should be " + props[k]); }
    } catch (e) { bad++; log("   ! " + what + ": cannot read " + k + " (" + e + ")"); }
  }
  return bad;
}

// GREP styles a style carries: its own plus those inherited along the "based on" chain
function grepCount(p) {
  var n = 0, i, q = p;
  while (q) {
    n += q.grep ? q.grep.length : 0;
    if (!q.basedOn) { break; }
    for (i = 0; i < SPEC.paragraph.length; i++) { if (SPEC.paragraph[i].name === q.basedOn) { q = SPEC.paragraph[i]; break; } }
  }
  return n;
}
function builtin(n) { return n.charAt(0) === "["; }
function findIn(list, name) {
  var i;
  for (i = 0; i < list.length; i++) { if (list[i].name === name) { return list[i]; } }
  return null;
}
function newPara(doc, name) {
  var a = doc.allParagraphStyles, i;
  for (i = 0; i < a.length; i++) { if (a[i].name === name && a[i].name.indexOf(PREFIX) !== 0) { return a[i]; } }
  return null;
}

function documentSettings(doc) {
  var d = SPEC.document, fo = {}, k, bp;
  setAll(doc.gridPreferences, d.grid, "baseline grid");
  setAll(doc.textPreferences, d.text, "text preferences");
  bp = doc.paragraphStyles[1];                       // [Basic Paragraph] (name is localised)
  setAll(bp, d.basic_paragraph, bp.name);
  for (k in d.footnotes) { if (d.footnotes.hasOwnProperty(k) && k !== "footnoteTextStyle" && k !== "footnoteMarkerStyle") { fo[k] = d.footnotes[k]; } }
  setAll(doc.footnoteOptions, fo, "Footnote Options");
  log("1. document: baseline grid " + d.grid.baselineDivision.toFixed(4) + " pt from " + d.grid.baselineStart.toFixed(3) +
      " pt; footnote options; superscript " + d.text.superscriptSize + "/" + d.text.superscriptPosition + " %");
}

function main() {
  // batch mode (tests): the caller passes the document in the global SROM_TARGET_DOC and never the active one
  var batch = typeof SROM_TARGET_DOC !== "undefined" && SROM_TARGET_DOC !== null;
  if (!batch && app.documents.length === 0) { alert("SROM styles: open the document first (blank, or a copy of an old one)."); return; }
  var doc = batch ? SROM_TARGET_DOC : app.activeDocument;
  DOC = doc;
  if (!batch && !confirm("SROM house style v3 for\r" + doc.name + "\r\rALL paragraph and character styles of this document are replaced by the " +
      "SROM set (text keeps its look through the mapping old → new). Run it on a blank document or a COPY. Continue?")) { return; }
  var oldUnits = app.scriptPreferences.measurementUnit;
  app.scriptPreferences.measurementUnit = MeasurementUnits.POINTS;
  var i, j, s, c, p, st, a, g, groups = {}, oldP = [], oldC = [], oldG = [], made = {}, bad = 0, target, cond, k, ok;

  log("SROM house style v3 — " + doc.name);
  documentSettings(doc);

  // 2a. move every existing style out of the way (renamed with a prefix; deleted at the end)
  a = doc.allParagraphStyles;
  for (i = 0; i < a.length; i++) { if (!builtin(a[i].name)) { oldP.push(a[i]); a[i].name = PREFIX + a[i].name; } }
  a = doc.allCharacterStyles;
  for (i = 0; i < a.length; i++) { if (!builtin(a[i].name)) { oldC.push(a[i]); a[i].name = PREFIX + a[i].name; } }
  for (i = 0; i < doc.paragraphStyleGroups.length; i++) { oldG.push(doc.paragraphStyleGroups[i]); }
  for (i = 0; i < doc.characterStyleGroups.length; i++) { oldG.push(doc.characterStyleGroups[i]); }
  for (i = 0; i < oldG.length; i++) { try { oldG[i].name = PREFIX + oldG[i].name; } catch (e0) {} }
  log("2. old styles set aside: " + oldP.length + " paragraph, " + oldC.length + " character");

  // 3a. character styles
  log("3. house styles");
  for (i = 0; i < SPEC.character.length; i++) {
    c = SPEC.character[i];
    s = doc.characterStyles.add({name: c.name});
    setAll(s, c.props, c.name);
    made["C:" + c.name] = s;
  }
  // 3b. paragraph styles: the root set first, then the folders, in spec order
  for (i = 0; i < SPEC.groups.length; i++) {
    g = SPEC.groups[i].name;
    if (g !== "") { groups[g] = doc.paragraphStyleGroups.add({name: g}); }
  }
  for (j = 0; j < 2; j++) {           // pass 0: root styles, pass 1: grouped styles (keeps the panel order)
    for (i = 0; i < SPEC.paragraph.length; i++) {
      p = SPEC.paragraph[i];
      if ((p.group === "") !== (j === 0)) { continue; }
      s = p.group === "" ? doc.paragraphStyles.add({name: p.name}) : groups[p.group].paragraphStyles.add({name: p.name});
      made["P:" + p.name] = s;
    }
  }
  for (i = 0; i < SPEC.paragraph.length; i++) {
    p = SPEC.paragraph[i]; s = made["P:" + p.name];
    try { s.basedOn = p.basedOn ? made["P:" + p.basedOn] : doc.paragraphStyles[0]; }
    catch (e1) { log("   ! " + p.name + ": based on " + p.basedOn + " (" + e1 + ")"); }
    setAll(s, p.props, p.name);
    if (p.bullet) {
      try {
        s.bulletsAndNumberingListType = ListType.BULLET_LIST;
        s.bulletChar.characterType = BulletCharacterType.UNICODE_ONLY;
        s.bulletChar.characterValue = p.bullet.char;
        s.bulletsTextAfter = p.bullet.after;
      } catch (e2) { log("   ! " + p.name + ": bullet (" + e2 + ")"); }
    }
    for (k = 0; p.tabs && k < p.tabs.length; k++) {
      try { s.tabStops.add({position: p.tabs[k].position, alignment: val("alignment", p.tabs[k].alignment), leader: p.tabs[k].leader}); }
      catch (e3) { log("   ! " + p.name + ": tab stop (" + e3 + ")"); }
    }
    for (k = 0; p.grep && k < p.grep.length; k++) {
      try { s.nestedGrepStyles.add({appliedCharacterStyle: made["C:" + p.grep[k].style], grepExpression: p.grep[k].expr}); }
      catch (e4) { log("   ! " + p.name + ": GREP " + p.grep[k].expr + " (" + e4 + ")"); }
    }
    for (k = 0; p.nested && k < p.nested.length; k++) {
      try {
        s.nestedStyles.add({appliedCharacterStyle: made["C:" + p.nested[k].style], delimiter: val("delimiter", p.nested[k].delimiter),
                            repetition: p.nested[k].repetition, inclusive: p.nested[k].inclusive});
      } catch (e5) { log("   ! " + p.name + ": nested style (" + e5 + ")"); }
    }
  }
  for (i = 0; i < SPEC.paragraph.length; i++) {
    p = SPEC.paragraph[i];
    if (p.next) { try { made["P:" + p.name].nextStyle = made["P:" + p.next]; } catch (e6) { log("   ! " + p.name + ": next style (" + e6 + ")"); } }
  }
  log("   " + SPEC.paragraph.length + " paragraph styles (" + SPEC.groups.length + " levels), " + SPEC.character.length + " character styles");

  // 2b. purge: each old style → its new style (text keeps its look), then the old folders
  log("4. old styles replaced");
  for (i = 0; i < oldP.length; i++) {
    var on = oldP[i].name.substr(PREFIX.length);
    target = null;
    for (j = 0; j < SPEC.paragraph.length && !target; j++) {
      cond = SPEC.paragraph[j].old_if && SPEC.paragraph[j].old_if[on];
      if (cond) {
        ok = true;
        for (k in cond) { if (cond.hasOwnProperty(k)) { try { if (!same(oldP[i][k], cond[k])) { ok = false; } } catch (e7) { ok = false; } } }
        if (ok) { target = made["P:" + SPEC.paragraph[j].name]; }
      }
    }
    for (j = 0; j < SPEC.paragraph.length && !target; j++) {
      a = SPEC.paragraph[j].old || [];
      for (k = 0; k < a.length; k++) { if (a[k] === on) { target = made["P:" + SPEC.paragraph[j].name]; } }
    }
    var known = target !== null;
    if (!target) { target = made["P:" + SPEC.para_fallback]; }
    try { oldP[i].remove(target); log("   " + on + "  →  " + target.name + (known ? "" : "   (unknown style)")); }
    catch (e8) { log("   ! remove " + on + ": " + e8); }
  }
  for (i = 0; i < oldC.length; i++) {
    var cn = oldC[i].name.substr(PREFIX.length), ct = null;
    for (j = 0; j < SPEC.character.length && !ct; j++) {
      a = SPEC.character[j].old || [];
      for (k = 0; k < a.length; k++) { if (a[k] === cn) { ct = made["C:" + SPEC.character[j].name]; } }
    }
    try { oldC[i].remove(ct ? ct : doc.characterStyles[0]); log("   " + cn + "  →  " + (ct ? ct.name : doc.characterStyles[0].name) + " (character)"); }
    catch (e9) { log("   ! remove character style " + cn + ": " + e9); }
  }
  for (i = 0; i < oldG.length; i++) { try { if (oldG[i].isValid) { oldG[i].remove(); } } catch (e10) { log("   ! remove folder: " + e10); } }

  // footnote styles now that the house Przypis exists
  try { doc.footnoteOptions.footnoteTextStyle = made["P:" + SPEC.document.footnotes.footnoteTextStyle]; } catch (e11) { log("   ! footnote style: " + e11); }
  try { doc.footnoteOptions.footnoteMarkerStyle = doc.characterStyles[0]; } catch (e12) { log("   ! footnote marker style: " + e12); }

  // 5. read everything back
  log("5. check (every value read back from InDesign)");
  bad += check(doc.gridPreferences, SPEC.document.grid, "baseline grid");
  bad += check(doc.textPreferences, SPEC.document.text, "text preferences");
  bad += check(doc.footnoteOptions, SPEC.document.footnotes, "Footnote Options");
  for (i = 0; i < SPEC.character.length; i++) { bad += check(made["C:" + SPEC.character[i].name], SPEC.character[i].props, SPEC.character[i].name); }
  for (i = 0; i < SPEC.paragraph.length; i++) {
    p = SPEC.paragraph[i]; s = made["P:" + p.name];
    bad += check(s, p.props, p.name);
    var bn = typeof s.basedOn === "string" ? s.basedOn : s.basedOn.name;
    if (bn !== (p.basedOn || doc.paragraphStyles[0].name)) { bad++; log("   ! " + p.name + ": based on " + bn); }
    if (s.nestedGrepStyles.length !== grepCount(p)) { bad++; log("   ! " + p.name + ": " + s.nestedGrepStyles.length + " GREP styles, should be " + grepCount(p)); }
    if (p.nested && s.nestedStyles.length !== p.nested.length) { bad++; log("   ! " + p.name + ": " + s.nestedStyles.length + " nested styles"); }
  }
  a = doc.allParagraphStyles; c = 0;
  for (i = 0; i < a.length; i++) { if (!builtin(a[i].name)) { c++; if (!made["P:" + a[i].name]) { bad++; log("   ! left over: " + a[i].name); } } }
  a = doc.allCharacterStyles; j = 0;
  for (i = 0; i < a.length; i++) { if (!builtin(a[i].name)) { j++; if (!made["C:" + a[i].name]) { bad++; log("   ! left over character style: " + a[i].name); } } }
  log("   the document now has " + c + " paragraph and " + j + " character styles");

  app.scriptPreferences.measurementUnit = oldUnits;
  var problems = 0;
  for (i = 0; i < LOG.length; i++) { if (LOG[i].indexOf("   !") === 0) { problems++; } }
  LOG.push(problems ? "RESULT: done with " + problems + " problem(s) — see lines marked !" : "RESULT: OK");
  var f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_style_setup.txt"); }
  catch (e13) { f = new File(Folder.desktop + "/srom_style_setup.txt"); }
  if (batch && typeof SROM_REPORT !== "undefined") { f = new File(SROM_REPORT); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(LOG.join("\r")); f.close(); }
  if (!batch) { alert(LOG.slice(-25).join("\r")); }
  return LOG[LOG.length - 1];
}

main();
