// srom_style_setup.jsx — builds the SROM house paragraph/character styles in the ACTIVE document.
// Generated by scripts/make_style_setup.py from indesign/style_spec.json — do not edit by hand.
// RUN ON A COPY OF THE TEMPLATE. What it does:
//   1. creates the style groups and styles (Podstawa + 9 groups); an existing old style is RENAMED into the
//      new name, so text already formatted with it keeps its formatting; two old styles for one new name
//      are merged (the second is deleted and replaced by the first);
//   2. sets "based on" and the typographic values of the house style (footnote style left untouched);
//   3. adds the GREP styles for non-breaking spaces (kanon §3.3) and gloss small caps;
//   4. deletes Word leftovers, replacing them with "Tekst" wherever used.
// A report is shown and saved next to the document (<name>_style_setup.txt).
//@target indesign

var SPEC = /*SPEC*/;
var LOG = [];
function log(s) { LOG.push(s); }

function allPara(doc) { return doc.allParagraphStyles; }
function findPara(doc, name) {
  var a = allPara(doc), i;
  for (i = 0; i < a.length; i++) { if (a[i].name === name) { return a[i]; } }
  return null;
}
function findChar(doc, name) {
  var a = doc.allCharacterStyles, i;
  for (i = 0; i < a.length; i++) { if (a[i].name === name) { return a[i]; } }
  return null;
}
function findGroup(doc, name) {
  var g = doc.paragraphStyleGroups, i;
  for (i = 0; i < g.length; i++) { if (g[i].name === name) { return g[i]; } }
  return doc.paragraphStyleGroups.add({name: name});
}

function setProp(obj, k, v, doc) {
  try {
    if (k === "justification") { obj.justification = Justification[v]; }
    else if (k === "capitalization") { obj.capitalization = Capitalization[v]; }
    else if (k === "gridAlignment") { obj.gridAlignment = GridAlignment[v]; }
    else if (k === "bulletChar") {
      obj.bulletsAndNumberingListType = ListType.BULLET_LIST;
      obj.bulletChar.characterType = BulletCharacterType.UNICODE_ONLY;
      obj.bulletChar.characterValue = v;
      obj.bulletsTextAfter = "^t";
    }
    else { obj[k] = v; }
  } catch (e) { log("   ! " + obj.name + ": could not set " + k + " = " + v + " (" + e + ")"); }
}

function applyProps(obj, props, doc) {
  var k;
  for (k in props) { if (props.hasOwnProperty(k)) { setProp(obj, k, props[k], doc); } }
}

function addGrep(style, rules, doc) {
  var i, j, cs, exists, g;
  for (i = 0; i < rules.length; i++) {
    cs = findChar(doc, rules[i].style);
    if (!cs) { log("   ! GREP: character style missing " + rules[i].style); continue; }
    exists = false;
    g = style.nestedGrepStyles;
    for (j = 0; j < g.length; j++) { if (g[j].grepExpression === rules[i].expr) { exists = true; } }
    if (!exists) {
      try { style.nestedGrepStyles.add({appliedCharacterStyle: cs, grepExpression: rules[i].expr}); }
      catch (e) { log("   ! GREP on " + style.name + ": " + e); }
    }
  }
}

// old style(s) -> the style with the new name (rename the first found, merge the rest into it)
function adopt(doc, name, olds, finder) {
  var target = finder(doc, name), i, o;
  for (i = 0; olds && i < olds.length; i++) {
    o = finder(doc, olds[i]);
    if (!o || o === target) { continue; }
    if (!target) {
      try { o.name = name; target = o; log("   renamed  " + olds[i] + "  →  " + name); }
      catch (e) { log("   ! rename " + olds[i] + ": " + e); }
    } else {
      try { o.remove(target); log("   merged   " + olds[i] + "  →  " + name); }
      catch (e2) { log("   ! merge " + olds[i] + ": " + e2); }
    }
  }
  return target;
}

function main() {
  if (app.documents.length === 0) { alert("SROM styles: open the template (a COPY) first."); return; }
  var doc = app.activeDocument;
  if (!confirm("SROM house style: rebuild the paragraph and character styles of\r" + doc.name +
               "\r\rRun this on a COPY of the template. Continue?")) { return; }
  var oldUnits = app.scriptPreferences.measurementUnit;
  app.scriptPreferences.measurementUnit = MeasurementUnits.POINTS;
  var i, j, c, s, g, grp, st, all = [], leftover, repl;

  log("SROM house style — " + doc.name);
  log("1. character styles");
  for (i = 0; i < SPEC.character.length; i++) {
    c = SPEC.character[i];
    s = adopt(doc, c.name, c.old, findChar);
    if (!s) { s = doc.characterStyles.add({name: c.name}); log("   created  " + c.name); }
    applyProps(s, c.props, doc);
  }
  for (c in SPEC.char_leftovers) {
    if (!SPEC.char_leftovers.hasOwnProperty(c)) { continue; }
    s = findChar(doc, c);
    if (s) {
      repl = SPEC.char_leftovers[c] ? findChar(doc, SPEC.char_leftovers[c]) : doc.characterStyles.item(0);
      try { s.remove(repl); log("   removed  char style " + c); } catch (e) { log("   ! remove char " + c + ": " + e); }
    }
  }

  log("2. paragraph styles");
  var base = findPara(doc, SPEC.base.name);
  if (!base) { base = doc.paragraphStyles.add({name: SPEC.base.name}); log("   created  " + SPEC.base.name); }
  for (i = 0; i < SPEC.groups.length; i++) {
    g = SPEC.groups[i];
    grp = findGroup(doc, g.name);
    for (j = 0; j < g.styles.length; j++) {
      st = g.styles[j];
      s = adopt(doc, st.name, st.old, findPara);
      if (!s) { s = grp.paragraphStyles.add({name: st.name}); log("   created  " + st.name); }
      try { if (s.parent !== grp) { s.move(LocationOptions.AT_END, grp); } } catch (e) { log("   ! move " + st.name + ": " + e); }
      all.push({style: s, spec: st, keep: g.keep_as_is === true});
    }
  }

  log("3. based on + values");
  try { base.basedOn = doc.paragraphStyles.item(0); } catch (e) {}
  applyProps(base, SPEC.base.props, doc);
  addGrep(base, SPEC.base.grep, doc);
  for (i = 0; i < all.length; i++) {
    if (all[i].keep) { continue; }
    if (all[i].spec.basedOn) {
      s = findPara(doc, all[i].spec.basedOn);
      if (s) { try { all[i].style.basedOn = s; } catch (e) { log("   ! basedOn " + all[i].spec.name + ": " + e); } }
    }
    applyProps(all[i].style, all[i].spec.props, doc);
    if (all[i].spec.grep) { addGrep(all[i].style, all[i].spec.grep, doc); }
  }

  log("4. Word leftovers");
  repl = findPara(doc, SPEC.leftovers.replace_with);
  for (i = 0; i < SPEC.leftovers.names.length; i++) {
    leftover = findPara(doc, SPEC.leftovers.names[i]);
    if (leftover) {
      try { leftover.remove(repl); log("   removed  " + SPEC.leftovers.names[i]); }
      catch (e) { log("   ! remove " + SPEC.leftovers.names[i] + ": " + e); }
    }
  }

  app.scriptPreferences.measurementUnit = oldUnits;
  var problems = 0;
  for (i = 0; i < LOG.length; i++) { if (LOG[i].indexOf("!") === 3) { problems++; } }
  LOG.push(problems ? "RESULT: done with " + problems + " problem(s) — see lines marked !" : "RESULT: OK");
  var f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_style_setup.txt"); }
  catch (e) { f = new File(Folder.desktop + "/srom_style_setup.txt"); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(LOG.join("\r")); f.close(); }
  alert(LOG.slice(-25).join("\r"));
}

main();
