// srom_final_pass.jsx — last pass after the text is flowed and the pages are final (Kanon § 3.6 "Łamanie").
// Generated by scripts/make_style_setup.py from indesign/style_spec.json ("final_pass") — do not edit by hand.
// Finds what only shows on the page:
//   SZEWC      first line of a paragraph alone at the foot of a column (min. 2 lines before a break)
//   BĘKART     last line of a paragraph alone at the top of a column (min. 2 lines after a break)
//   WDOWA      last line of a paragraph too short (fewer than N characters) or only the end of a hyphenated word
//   ŚRÓDTYTUŁ  a heading closes a column
//   SIEROTKA   a one-letter word (a i o u w z) at the end of a line
//   PÓŁPAUZA   a line starting with a dash (outside lists)
//   URL        a URL broken other than after "/" or before "."
//   DZIELENIE  a capitalised word (name, abbreviation) or a number/call number split at the end of a line
//   OVERSET, fonts other than the house font, missing fonts; hyphen at a page turn (info)
// Mode "fix": SZEWC, BĘKART and WDOWA are remedied as vol. 18 did by hand — paragraph tracking −5/−10/+5/+10 on the
// paragraph or one of the three before it in the same column; a change is kept only if that problem goes and no new
// one appears in its column and the next. Everything the script changes is ONE undo step (Edit ▸ Undo).
// Scope: the story with the text cursor, else every story of the document with more than 300 characters.
// Report next to the document: <name>_final_pass.txt.   Notes are checked too (a split footnote is a paragraph).
//@target indesign

var CONF = /*CONF*/;
var LOG = [], DOC = null, T0 = new Date().getTime();
function outOfTime() { return new Date().getTime() - T0 > CONF.time_budget_s * 1000; }
function log(s) { LOG.push(s); }
function has(list, x) { var i; for (i = 0; i < list.length; i++) { if (list[i] === x) { return true; } } return false; }
function styleName(p) { try { return p.appliedParagraphStyle.name; } catch (e) { return ""; } }
function head(p) { var s = ""; try { s = p.contents; } catch (e) {} s = s.replace(/[\r\n\t]+/g, " "); return s.length > 45 ? s.substr(0, 45) + "…" : s; }

// column of a line: the frame, and for multi-column frames the column
function colOf(line) {
  var f;
  try { f = line.parentTextFrames[0]; } catch (e) { return null; }
  if (!f || !f.isValid) { return null; }
  var key = String(f.id), n = 1;
  try { n = f.textFramePreferences.textColumnCount; } catch (e1) {}
  if (n > 1) {
    var b = f.geometricBounds, w = (b[3] - b[1]) / n;
    key += ":" + Math.floor((line.horizontalOffset - b[1]) / w);
  }
  return key;
}
function pageOf(line) {
  try { var pg = line.parentTextFrames[0].parentPage; return pg ? pg.name : "?"; } catch (e) { return "?"; }
}
function isRecto(line) {
  try { return line.parentTextFrames[0].parentPage.side === PageSideOptions.RIGHT_HAND; } catch (e) { return false; }
}

// all problems of one paragraph -> [{kind, page, para, text}]
function paraIssues(p, out) {
  var st = styleName(p), ls, n, c0, c1, cl, cm, txt, last, prev, i, lc, words;
  if (has(CONF.skip_styles, st)) { return; }
  try { if (p.parent.constructor.name === "Cell") { return; } } catch (e0) {}
  ls = p.lines; n = ls.length;
  if (n === 0 || colOf(ls[0]) === null) { return; }           // overset: not on a page
  lc = ls.everyItem().contents;
  if (has(CONF.headings, st)) {
    // a heading closes a column: its last line and the next paragraph's first line are in different columns
    try {
      var np = nextPara(p);
      if (np && np.lines.length && colOf(np.lines[0]) !== colOf(ls[n - 1])) {
        out.push({kind: "ŚRÓDTYTUŁ", page: pageOf(ls[n - 1]), para: p, text: head(p)});
      }
    } catch (e1) {}
  }
  if (n >= 2 && !has(CONF.headings, st)) {
    c0 = colOf(ls[0]); c1 = colOf(ls[1]); cm = colOf(ls[n - 2]); cl = colOf(ls[n - 1]);
    if (c0 !== null && c1 !== null && c0 !== c1) { out.push({kind: "SZEWC", page: pageOf(ls[0]), para: p, text: head(p)}); }
    if (cm !== null && cl !== null && cm !== cl) { out.push({kind: "BĘKART", page: pageOf(ls[n - 1]), para: p, text: head(p)}); }
    if (has(CONF.short_last_line, st)) {
      last = lc[n - 1].replace(/[\r\n\s]+$/, ""); prev = lc[n - 2];
      words = last.split(/\s+/);
      var split = /[A-Za-zÀ-ž]$/.test(prev) && words.length === 1;       // previous line ends inside a word
      var bare = last.replace(/[.,;:!?…)\]»”’"]+$/, "");
      if (bare === "") {
        out.push({kind: "PUSTY WIERSZ", page: pageOf(ls[n - 1]), para: p, text: "spaces or a line break at the paragraph end make an empty line — " + head(p)});
      } else if (bare.length < CONF.min_last_line_chars || (split && bare.length <= CONF.max_fragment_chars)) {
        out.push({kind: "WDOWA", page: pageOf(ls[n - 1]), para: p, text: "„" + last + "” — " + head(p)});
      }
    }
  }
  for (i = 0; i < n; i++) {
    txt = lc[i];
    if (i < n - 1 && /(^|\s)[aiouwzAIOUWZ] $/.test(txt)) { out.push({kind: "SIEROTKA", page: pageOf(ls[i]), para: p, text: "„…" + txt.slice(-20) + "”"}); }
    if (i > 0 && /^[–—] /.test(txt) && !has(CONF.lists, st)) { out.push({kind: "PÓŁPAUZA", page: pageOf(ls[i]), para: p, text: "„" + txt.substr(0, 25) + "…”"}); }
    if (i < n - 1 && /(https?:\/\/|www\.|doi\.org)\S*$/.test(txt) && !/\/$/.test(txt) && !/^\./.test(lc[i + 1])) {
      out.push({kind: "URL", page: pageOf(ls[i]), para: p, text: "„…" + txt.slice(-30) + "”"});
    }
    if (i < n - 1 && /[A-Za-zÀ-ž0-9]$/.test(txt) && /^[A-Za-zÀ-ž0-9]/.test(lc[i + 1]) && !/(https?:\/\/|www\.)\S*$/.test(txt)) {
      var tok = txt.split(/\s/).pop();
      if (/^[A-ZÀ-ÖØ-ÞĄĆĘŁŃÓŚŹŻ]/.test(tok) || /\d/.test(tok)) { out.push({kind: "DZIELENIE", page: pageOf(ls[i]), para: p, text: "„" + tok + "-” (" + head(p) + ")"}); }
    }
  }
  // info: hyphen at a page turn (last line of a right-hand page ends inside a word)
  for (i = 0; i < n - 1; i++) {
    if (isRecto(ls[i]) && colOf(ls[i]) !== colOf(ls[i + 1]) && /[A-Za-zÀ-ž]$/.test(lc[i]) && /^[a-zà-ž]/.test(lc[i + 1])) {
      out.push({kind: "info: dzielenie na odwrocie", page: pageOf(ls[i]), para: p, text: "„…" + lc[i].slice(-20) + "”"});
    }
  }
}
function storyIssues(story) {
  var out = [], ps = story.paragraphs, i, fns = story.footnotes, j, k;
  for (i = 0; i < ps.length; i++) {
    try { if (ps[i].lines.length && colOf(ps[i].lines[0]) === null) { break; } } catch (e) {}   // the rest is overset
    paraIssues(ps[i], out);
  }
  for (j = 0; j < fns.length; j++) { for (k = 0; k < fns[j].paragraphs.length; k++) { paraIssues(fns[j].paragraphs[k], out); } }
  return out;
}
function isNote(p) { try { return p.parent.constructor.name === "Footnote"; } catch (e) { return false; } }
function prevPara(p) { try { var q = p.parentStory.paragraphs.previousItem(p); return q && q.isValid ? q : null; } catch (e) { return null; } }
function nextPara(p) { try { var q = p.parentStory.paragraphs.nextItem(p); return q && q.isValid ? q : null; } catch (e) { return null; } }
function fixable(k) { return k === "SZEWC" || k === "BĘKART" || k === "WDOWA" || k === "PUSTY WIERSZ"; }
// white space (spaces, forced line breaks) before the paragraph end: removed — it carries nothing
function stripEnd(p) {
  var c = p.characters, k = c.length - 1, n = 0;
  if (k >= 0 && c[k].contents === "\r") { k--; }
  while (k >= 0 && (c[k].contents === " " || c[k].contents === SpecialCharacters.FORCED_LINE_BREAK || c[k].contents === "\n" ||
         c[k].contents === SpecialCharacters.NONBREAKING_SPACE)) { c[k].remove(); k--; n++; }
  return n;
}
function same(a, b) { return a.kind === b.kind && a.para.index === b.para.index && isNote(a.para) === isNote(b.para) && a.page === b.page; }
function trackingOf(p) { var t = p.tracking; return typeof t === "number" ? t : null; }

// issues in the paragraphs around p: from three paragraphs before it to the end of the column after its own
function localIssues(p) {
  var out = [], q = p, i, c0, c, seen = 0, passed = false, r;
  if (isNote(p)) { paraIssues(p, out); return out; }
  for (i = 0; i < 3; i++) { r = prevPara(q); if (!r) { break; } q = r; }
  try { c0 = colOf(q.lines[-1]); } catch (e0) { c0 = null; }
  for (i = 0; q && i < 60; i++) {                   // at most 60 paragraphs; never into overset text
    paraIssues(q, out);
    if (q.index === p.index) { passed = true; }
    try { c = colOf(q.lines[-1]); } catch (e) { c = null; }
    if (c === null) { break; }
    if (c !== c0) { seen++; c0 = c; }
    if (passed && seen >= 2) { break; }
    q = nextPara(q);
  }
  return out;
}
function tryFix(iss) {
  var p = iss.para, cands = [p], q = p, i, j, d, t0, before, after, ok, still, k, n0;
  if (!isNote(p)) {
    for (i = 0; i < 3; i++) {                      // up to three paragraphs before it, ending in its column(s)
      q = prevPara(q);
      if (!q || (colOf(q.lines[-1]) !== colOf(p.lines[0]) && colOf(q.lines[-1]) !== colOf(p.lines[-1]))) { break; }
      if (!has(CONF.headings, styleName(q))) { cands.push(q); }
    }
  }
  if (iss.kind === "PUSTY WIERSZ") {
    k = stripEnd(p); p.parentStory.recompose();
    return k ? k + " white-space character(s) removed at the paragraph end" : null;
  }
  var overBefore = p.parentStory.overflows;
  before = localIssues(p).length;
  for (i = 0; i < cands.length; i++) {
    q = cands[i]; t0 = trackingOf(q);
    if (t0 === null) { continue; }                        // mixed tracking: leave it to the typesetter
    for (j = 0; j < CONF.tracking_steps.length; j++) {
      d = CONF.tracking_steps[j];
      if (Math.abs(t0 + d) > CONF.max_tracking) { continue; }
      n0 = q.lines.length;
      q.tracking = t0 + d; q.parentStory.recompose();
      after = localIssues(p);
      still = false;
      for (k = 0; k < after.length; k++) { if (same(after[k], iss)) { still = true; } }
      ok = !still && after.length < before && (overBefore || !q.parentStory.overflows);   // never creates overset
      if (ok) { return "tracking " + (d > 0 ? "+" : "") + d + " on „" + head(q) + "” (p. " + pageOf(q.lines[0]) + ")"; }
      q.tracking = t0; q.parentStory.recompose();
    }
  }
  return null;
}

function run(doc, mode, stories) {
  var s, i, j, iss, all = [], fixed = 0, left = 0, r, fonts, f, bad;
  log("SROM final pass — " + doc.name + " — mode: " + (mode === "fix" ? "fix and report" : "report only"));
  for (s = 0; s < stories.length; s++) {
    var story = stories[s];
    if (story.overflows) { log("   ! OVERSET: story „" + head(story.paragraphs[0]) + "” has text that does not fit"); left++; }
    iss = storyIssues(story);
    if (mode === "fix") {
      for (i = 0; i < iss.length; i++) {
        if (!fixable(iss[i].kind)) { continue; }
        if (outOfTime()) { log("   ! time budget (" + CONF.time_budget_s + " s) used up: the rest reported, not fixed"); break; }
        var now = localIssues(iss[i].para), present = false;
        for (j = 0; j < now.length; j++) { if (same(now[j], iss[i])) { present = true; } }
        if (!present) { iss[i].done = "gone after an earlier fix"; continue; }
        r = tryFix(iss[i]);
        if (r) { iss[i].done = r; fixed++; }
      }
      iss = storyIssues(story).concat(doneOnly(iss));
    }
    all = all.concat(iss);
  }
  for (i = 0; i < all.length; i++) {
    if (all[i].done) { log("   fixed  p. " + all[i].page + "  " + all[i].kind + "  " + all[i].text + "  → " + all[i].done); }
  }
  for (i = 0; i < all.length; i++) {
    if (all[i].done) { continue; }
    if (all[i].kind.indexOf("info") === 0) { log("   info   p. " + all[i].page + "  " + all[i].kind.substr(6) + "  " + all[i].text); continue; }
    left++; log("   ! p. " + all[i].page + "  " + all[i].kind + "  " + all[i].text);
  }
  fonts = doc.fonts; bad = [];
  for (f = 0; f < fonts.length; f++) {
    try {
      if (fonts[f].status !== FontStatus.INSTALLED) { bad.push(fonts[f].name + " (missing)"); }
      else if (fonts[f].fontFamily !== CONF.font && !has(CONF.other_fonts_ok, fonts[f].fontFamily)) { bad.push(fonts[f].name); }
    } catch (e2) {}
  }
  if (bad.length) { left++; log("   ! fonts other than " + CONF.font + " or missing: " + bad.join(", ")); }
  log("   " + fixed + " fixed, " + left + " to see by eye");
  return left;
}
function doneOnly(list) { var o = [], i; for (i = 0; i < list.length; i++) { if (list[i].done) { o.push(list[i]); } } return o; }

function main() {
  var batch = typeof SROM_TARGET_DOC !== "undefined" && SROM_TARGET_DOC !== null;
  if (!batch && app.documents.length === 0) { alert("SROM final pass: open the document first."); return; }
  var doc = batch ? SROM_TARGET_DOC : app.activeDocument, mode = batch ? SROM_MODE : null, stories = [], i;
  DOC = doc;
  if (!batch) {
    var dlg = app.dialogs.add({name: "SROM – ostatni przebieg (Kanon § 3.6)"}), col = dlg.dialogColumns.add(), rb;
    col.staticTexts.add({staticLabel: "Szewce, bękarty, wdowy, śródtytuły na dole łamu, sierotki, URL, dzielenie, overset, fonty."});
    rb = col.radiobuttonGroups.add();
    rb.radiobuttonControls.add({staticLabel: "Tylko raport", checkedState: true});
    rb.radiobuttonControls.add({staticLabel: "Popraw (światło akapitu ±5/±10) i raport — jeden krok cofania"});
    if (!dlg.show()) { dlg.destroy(); return; }
    mode = rb.selectedButton === 1 ? "fix" : "report"; dlg.destroy();
  }
  try { if (!batch && app.selection.length && app.selection[0].parentStory) { stories.push(app.selection[0].parentStory); } } catch (e) {}
  if (!stories.length) {
    for (i = 0; i < doc.stories.length; i++) { if (doc.stories[i].length > 300 && doc.stories[i].textContainers.length && doc.stories[i].textContainers[0].parentPage) { stories.push(doc.stories[i]); } }
  }
  var oldUnits = app.scriptPreferences.measurementUnit;
  app.scriptPreferences.measurementUnit = MeasurementUnits.POINTS;
  var left = run(doc, mode, stories);
  app.scriptPreferences.measurementUnit = oldUnits;
  LOG.push(left ? "RESULT: " + left + " to see by eye — lines marked !" : "RESULT: OK");
  var f;
  try { f = new File(doc.filePath + "/" + doc.name.replace(/\.indd$/i, "") + "_final_pass.txt"); }
  catch (e3) { f = new File(Folder.desktop + "/srom_final_pass.txt"); }
  if (batch && typeof SROM_REPORT !== "undefined") { f = new File(SROM_REPORT); }
  f.encoding = "UTF-8";
  if (f.open("w")) { f.write(LOG.join("\r")); f.close(); }
  if (!batch) { alert(LOG.slice(0, 40).join("\r") + (LOG.length > 40 ? "\r… (full report: " + f.name + ")" : "")); }
  return LOG[LOG.length - 1];
}

if (typeof SROM_TARGET_DOC !== "undefined" && SROM_TARGET_DOC !== null) { main(); }
else { app.doScript(main, ScriptLanguage.JAVASCRIPT, undefined, UndoModes.ENTIRE_SCRIPT, "SROM final pass"); }
